### ISSUE TITLE
Sliders not responsive

### ISSUE THREAD

**Issue by nathan-foo** [tx-appdev/vct-hackathon#15]
Sliders are not responsive, so when the video size changes the cards do not adjust.

<img width="1249" alt="Screenshot 2024-10-01 at 11 42 35 PM" src="https://github.com/user-attachments/assets/9b124e68-fe86-474c-8578-1c65ecb08f1b">

**Comment by Ruler10123** [comment]
We could leave it as unresponsive as well, because that's what ChatGPT does on their OpenAI website
